
-- Create the listings table
CREATE TABLE IF NOT EXISTS public.listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Have', 'Need')),
    city TEXT NOT NULL,
    county TEXT,
    contact_email TEXT NOT NULL,
    views INTEGER DEFAULT 0
);

-- Enable Row Level Security
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read listings
CREATE POLICY "Allow public read access" 
ON public.listings FOR SELECT 
TO anon 
USING (true);

-- Create policy to allow anyone to insert listings
CREATE POLICY "Allow public insert access" 
ON public.listings FOR INSERT 
TO anon 
WITH CHECK (true);

-- Create policy to allow anyone to delete listings
CREATE POLICY "Allow public delete access" 
ON public.listings FOR DELETE 
TO anon 
USING (true);

-- Optional: Create an index on city for faster filtering
CREATE INDEX IF NOT EXISTS idx_listings_city ON public.listings(city);
