
-- Create the listings table
CREATE TABLE IF NOT EXISTS public.listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Have', 'Need')),
    city TEXT NOT NULL,
    county TEXT,
    contact_name TEXT,
    contact_email TEXT,
    telegram_username TEXT,
    preferred_contact TEXT DEFAULT 'email',
    contact_info TEXT,
    views INTEGER DEFAULT 0
);

-- Enable Row Level Security
ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anyone to read listings
CREATE POLICY "Allow public read access" 
ON public.listings FOR SELECT 
TO anon 
USING (true);

-- Create policy to allow anyone to insert listings
CREATE POLICY "Allow public insert access" 
ON public.listings FOR INSERT 
TO anon 
WITH CHECK (true);

-- Create policy to allow anyone to delete listings
CREATE POLICY "Allow public delete access" 
ON public.listings FOR DELETE 
TO anon 
USING (true);

-- Create an index on city for faster filtering
CREATE INDEX IF NOT EXISTS idx_listings_city ON public.listings(city);

-- Create table to track unique views by IP
CREATE TABLE IF NOT EXISTS public.listing_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT REFERENCES public.listings(id) ON DELETE CASCADE,
    ip_address TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(listing_id, ip_address)
);

-- Enable RLS on listing_views
ALTER TABLE public.listing_views ENABLE ROW LEVEL SECURITY;

-- Allow public to insert into listing_views
CREATE POLICY "Allow public insert to listing_views" 
ON public.listing_views FOR INSERT 
TO anon 
WITH CHECK (true);

-- Create atomic IP-based view counter function
CREATE OR REPLACE FUNCTION increment_views(listing_id BIGINT, user_ip TEXT)
RETURNS void AS $$
BEGIN
    -- Only increment if this IP hasn't viewed this listing before
    INSERT INTO public.listing_views (listing_id, ip_address)
    VALUES (listing_id, user_ip)
    ON CONFLICT (listing_id, ip_address) DO NOTHING;

    -- Update the main listings table count if the insert happened
    IF FOUND THEN
        UPDATE public.listings
        SET views = COALESCE(views, 0) + 1
        WHERE id = listing_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
